include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    one_member_abstracts: ignore
    document_ignores: ignore

linter:
  rules:
    public_member_api_docs: true
    document_ignores: true
