include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    depend_on_referenced_packages: ignore
    avoid_positional_boolean_parameters: ignore
  language:
    strict-inference: false
    strict-raw-types: false
    strict-casts: false

linter:
  rules:
    public_member_api_docs: false
    omit_local_variable_types: false
    lines_longer_than_80_chars: false
    unnecessary_lambdas: false
    prefer_int_literals: false
    library_private_types_in_public_api: false
    unawaited_futures: false
    avoid_dynamic_calls: false
    flutter_style_todos: false
    cast_nullable_to_non_nullable: false
    avoid_positional_boolean_parameters: false
    require_trailing_commas: false
    unnecessary_null_checks: false
