name: presentation
description: A module containing all the UI widgets and UI logic.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  application:
    path: ../application
  beamer: ^1.6.1
  bloc: ^8.1.4
  collection: 1.18.0
  core:
    path: ../../core
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  domain:
    path: ../domain
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_keyboard_visibility: ^6.0.0
  flutter_phoenix: ^1.1.1
  flutter_smart_dialog: ^4.9.7
  flutter_styled_toast: ^2.2.1
  flutter_svg: ^2.0.10
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  go_router: ^14.2.3
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  page_transition: ^2.1.0
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.6.0
  go_router_builder: ^2.7.1
  very_good_analysis: ^6.0.0
# dependency_overrides:
#   logger: 1.3.0
flutter:
  uses-material-design: true

  assets:
    - assets/
  #   - assets/images/payment_methods/
  #   - assets/images/stamp_card/
  #   - assets/images/rappit/
  #   - assets/images/profile_view/
  #   - assets/images/rewards_view/
  #   - assets/lottie/
  #   - assets/gif/
  # fonts:
  #   - family: PuregoIcons
  #     fonts:
  #       - asset: assets/fonts/PuregoIcons.ttf
flutter_gen:
  output: lib/assets/
  integrations:
    flutter_svg: true
    lottie: true
  assets:
    outputs:
      package_parameter_enabled: true

  module:
    androidX: true
    androidPackage: {{org_name.dotCase()}}.presentation
    iosBundleIdentifier: {{org_name.dotCase()}}.presentation
