include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    depend_on_referenced_packages: false
  language:
    strict-inference: false
    strict-raw-types: false

linter:
  rules:
    public_member_api_docs: true
    omit_local_variable_types: false
    lines_longer_than_80_chars: false
    unnecessary_lambdas: false
    prefer_int_literals: false
    comment_references: false
    document_ignores: true
