include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    strict-inference: false
    strict-raw-types: false

linter:
  rules:
    public_member_api_docs: true
    omit_local_variable_types: false
    lines_longer_than_80_chars: false
    unnecessary_lambdas: false
    prefer_int_literals: false
    require_trailing_commas: false
    non_constant_identifier_names: false
